apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:5eGHyCu9NAwl1rfVwg==,iv:FW6eVXhKQHoad6olcmROydqIf4z4T3z3EFvxpEwE4kw=,tag:y6L93KdrvscDaIKe3NNRyQ==,type:str]
    admin-user: ENC[AES256_GCM,data:3/AN0x8=,iv:lS9G83yJ2kr8iFONJAZSLlIEjiBQZHNhivDtuKUFBkM=,tag:yYJqvKliu96XX7a5R66VUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rej4wfl3ks23m6yjxus5f7zf2fkwx7gu6fw5f4w7t2r87zvsjuyqgnwj8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTkZtYVdOcnNycm1rTjUw
            L0o3a1pTMFBocm8ybUI4cFNPY2VtV3NQUERnCkkvYXlHNXRxSmJBMDNKQmxNeWda
            aTROcm5JVlYwZFppZVM0RHhqdkhhRFUKLS0tIEpCSTVYWk5WMHovOEZiQ2Zzc1Zl
            bFFiTUhBUktQNFBseUlTNXJUSUNFUjQKc2mKZYY+p6OxFB6jn/VXJOs+0gNh/n0R
            qDiRbO4XugY69BBS0yBSxjI6HrN2/lZzBtI5T4wPSNS0UGZCyQzn7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T05:36:03Z"
    mac: ENC[AES256_GCM,data:DGl/7HAHGrRodyAXoy49Q+ssqUmTTza0sG9O9G/FKme8RYAPIX56wVkA8vNMXEy3vtcnzTfKc5pyNrBI8NCdsAoS2xoMzpm169pLQ0NpE2KEWFGIRLJZKCBL+ERVV5f7NCLkesxkxsDSx/utcCg6ixWLQPL8m/qXtg5SF9O4iQw=,iv:0+mX5dIm5cNHAD7Q4O73DQR9YQrpPxwOnyT6ZXsSjFA=,tag:J/Y/cOiGV46vbPVUqhcTcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
