apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:t8J6rxbbFFjURUuYJJ1HwqaPzLAGBxA0qhBcBlATGKkP1rTLfv+vmdbFxnjhUQGkRCSrqEHVV1VXHtUa,iv:HdMSMYOVIbMGaafhn+QWEAdNtTXUCR0qU9jiCQg/dVk=,tag:fGF+s0jKrOzSuFZ1a/phew==,type:str]
    username: ENC[AES256_GCM,data:kDdQzHU=,iv:Cdlhtd70ubTUdb/bY5JPEuvIHx9A+ugodCIpe8uZMaQ=,tag:+8kZI0n5IYw2nc8NfsFk/w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rej4wfl3ks23m6yjxus5f7zf2fkwx7gu6fw5f4w7t2r87zvsjuyqgnwj8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydUhsbEVnTDRRTEh1L01I
            Q0V2dEE4ZHlpTitONC9wRFp1VVlzWUM5ZFZJCnFwaUZRaFdjWEJUZytVSzdWWHYw
            Q1k0em1jSnpZN2R1NmhWSDZ0UmxwTjQKLS0tIE9oQmtvL29sT20xRDdHUGc2OGFR
            Uzk4dkF2ZUZNc2drMmVlb2NpU3hGQ2sKHXDX1YHI95g4gMbGUbkSxGlDFCgQk7vz
            dH/diET5oP6ahbZw+XzsrMugN4253YtMhOh7pBBNGDcCjctkz0i+TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T04:48:38Z"
    mac: ENC[AES256_GCM,data:VlvxtVzSg97Ehd3TvXpfF3El98w7vKLOO9bUbp96hsnUIUurd0SAQdaeXEeViHFZ6f8eeCqYFSK6o61hwXrkUDjwBldm4XXocMiL7F/Gt/rwo4fIWKhx0orwoul72dFduof886hS507FOA32pNIdOMOdZtFZQ72tsITNR8l6zhI=,iv:8yprkUWn+Tw8XsPoTGTz4vtXUZ4K2NkBzDGzhQE3PLw=,tag:8GYRT2BXFCqm10qRQaYbKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
