apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:21YIUNI0g2eCc+ieDVwMG/Q+h+M6GVemJgrBW2egKILvxNZM,iv:nLkjRc1cNZF1p9EUe/iSyAGuv+ahh+nV83NNcfGQrpk=,tag:YR2VPq+KFlTmiCy6KjfCOw==,type:str]
    credentials.json: ENC[AES256_GCM,data:mIlGtGbf5ifnB2YadTbPdnPW/+6iHRxmP1QxY190UuUe93+OCQuAtl5LP4iVuYw9N6SmVMC5pGBYlOIpiyEYmWvMQYby6/jgtl/Qkftxh1zXPVv9xKJefzG0ieiP1oNmextsE4CRUSO9Bgs4bF1/Bp4IQ/Og2EFjRsEhPGTsQPNdehzuL64bCXuBtoeDse2eKJ3cV+pLggZVrL+r6rDV5L4BwzHHy/0u29lawzdEiw==,iv:rPkEO5Q0ZnWgrAgj/sbgYMuW6KU4PMRhoo58TT0nBr4=,tag:vDPbxqTd3o/mW90dXYedTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rej4wfl3ks23m6yjxus5f7zf2fkwx7gu6fw5f4w7t2r87zvsjuyqgnwj8m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eDMwYm15emtQTENTSWxQ
            OU1HT202R3JROWlaZ1p1dzBaTzBvY0NhZ1RJCloxL0RDOFlsbUwvZzlHUFd0U1dk
            RmRaMnlqRlkxVjVFWDdrZCtXalN4S28KLS0tIFhhc2hRMGd3V3RBK2UzUWVQMWV4
            cVFBNnRTOXRTTEdjZy9uRHpZc2ljRmcK4NYp1t7dhKrhTtOzka4XWrCuaqtT1tcc
            mbahVVLfSXzs8RWPfx6gAaZg19Aj2NQVTCHtAEolaSOufSDgOQFoGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T04:48:12Z"
    mac: ENC[AES256_GCM,data:7SHf9pgIqIotyB9RmzVQwloTB72eglW9X8iIGclDulhUyLATgO1eiAuBe1d83gdTHm9pTPAXZTaqkdLo7OOAAyZiLQRm/NfoghGVP0cCr0QQ3MfXqPFDOmUASIPLMHxb+P6IN/rMm15gwr/L5kOpeIxeVj9mmGkOlva4Jbo/qBk=,iv:egepJU5GT4UitG24kl6J3uCr7pCa/Yc//cajoLKOdeQ=,tag:flRd7zALfgr69gtHbG+0Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
